"""empty message

Revision ID: f2512412c77a
Revises: 
Create Date: 2018-01-20 15:14:09.950721

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f2512412c77a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('email_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('email_group_id', sa.Integer(), nullable=True),
    sa.Column('email_subject', sa.String(length=128), nullable=True),
    sa.Column('email_content', sa.Text(), nullable=True),
    sa.Column('timestamp', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('is_send', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_group_id'], ['email_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_is_send'), 'email_events', ['is_send'], unique=False)
    op.create_index(op.f('ix_email_events_timestamp'), 'email_events', ['timestamp'], unique=False)
    op.create_table('email_group2addresses',
    sa.Column('email_group_id', sa.Integer(), nullable=False),
    sa.Column('email_address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_address_id'], ['email_addresses.id'], ),
    sa.ForeignKeyConstraint(['email_group_id'], ['email_groups.id'], ),
    sa.PrimaryKeyConstraint('email_group_id', 'email_address_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_group2addresses')
    op.drop_index(op.f('ix_email_events_timestamp'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_is_send'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_table('email_groups')
    op.drop_table('email_addresses')
    # ### end Alembic commands ###
